name: earthquake
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  audio_video_progress_bar: ^1.0.1
  avatar_glow: ^2.0.2
  cached_network_image: ^3.2.3
  convex_bottom_bar: ^3.2.0
  expandable: ^5.0.1
  file_picker: ^5.2.6
  flutter:
    sdk: flutter
  flutter_html: ^2.1.2
  flutter_localizations:
    sdk: flutter
  flutter_neumorphic: ^3.2.0
  flutter_screenutil: ^5.6.0
  flutter_sms: ^2.3.3
  flutter_sound: ^9.2.13
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.4.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.3.0
  health: ^4.3.0
  hexcolor: ^3.0.1
  http: ^0.13.6
  http_parser: ^4.0.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  loading_animation_widget: ^1.2.0+4
  path_provider: ^2.0.15
  permission_handler: ^10.3.0
  persistent_bottom_nav_bar: ^5.0.2
  pin_code_fields: ^7.4.0
  provider: ^6.0.5
  restart_app: ^1.1.2
  shared_preferences: ^2.1.2
  url_launcher: ^6.1.11

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.4
  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Taj
      fonts:
        - asset: assets/fonts/Tajawal.ttf
